// Auto-generated by compile-package-info.js
// Do not change directly
const packageInfo = {
    "name": "Joplin",
    "version": "1.0.193",
    "description": "Joplin for Desktop",
    "main": "main.js",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/laurent22/joplin.git"
    },
    "author": "Laurent Cozic",
    "license": "MIT",
    "bugs": {
        "url": "https://github.com/laurent22/joplin/issues"
    },
    "homepage": "https://github.com/laurent22/joplin#readme",
    "build": {
        "appId": "net.cozic.joplin-desktop"
    }
};
module.exports = packageInfo;